---
title: "R Notebook"
output: html_notebook
#tutorial: https://bodowinter.com/tutorial/bw_LME_tutorial2.pdf
#youtube: https://www.youtube.com/watch?v=u1ePV1ntMNs&t=297s&ab_channel=LiquidBrainBioinformatics
---

```{r}
library(lmerTest)
library(Matrix)
library(bayestestR)
o_diffRF <- read.csv("C:\\Users\\User\\Cloud-Drive\\BigFiles\\OmissionExpOutput\\mix_modeling\\mm_6_sub-ses-posnegClust-senior10-manyTimeWin_diffRF.csv")
o_sepRF <- read.csv("C:\\Users\\User\\Cloud-Drive\\BigFiles\\OmissionExpOutput\\mix_modeling\\mm_6_sub-OrOf-ses-posnegClust-senior10-manyTimeWin.csv")
output_dir <- "C:\\Users\\User\\Cloud-Drive\\BigFiles\\OmissionExpOutput\\mix_modeling"
# head(omissionResponse)
# tail(omissionResponse)
# str(omissionResponse)
# colnames(omissionResponse)
# summary(omissionResponse)
# which(is.na(omissionResponse$ampAvg)) # or which(!complete.cases(politeness))

```

```{r}
boxplot(ampAvg_neg_diffRF ~ ses ,col=c("white","lightgray"),data=subset(o_diffRF, timeWin == "400-444")) # what are the dots? 
#boxplot(ampAvg_neg ~ ses ,col=c("white","lightgray"),data=subset(o_sepRF)) # what are the dots? 
```


```{r}
### orig plan: 
# for modeling the contribution of each fixed effect
#omissionResponse.model = lmer(ampAvg ~ expectation +numBlock + numTrial +(1|sub),data=omissionData)
```

```{r}
#"sub" "ses" "block_type" "timeWin" "seniority" 
wantedTimeWin <- "100-200" 
wantedSes <- "wake_morning" 

o_diffRF.null <- lmer(ampAvg_pos_diffRF ~ (1|sub/seniority) , data=subset(o_diffRF, timeWin == wantedTimeWin), REML=FALSE)
o_diffRF.model<-lmer(ampAvg_pos_diffRF ~ + ses + (1|sub/seniority) , data=subset(o_diffRF, timeWin == wantedTimeWin), REML=FALSE)

o_diffRF.model
print("*********************************")
anova(o_diffRF.null,o_diffRF.model)
print("*********************************")
# Calculate Bayes Factor
model_output <- bayesfactor_models(o_diffRF.null,o_diffRF.model,denominator=o_diffRF.null) 
# view Bayes Factor output
model_output
```

```{r}
################ Doesn't includes variable 'block_type'. Instead includes difference between fixed-rand ##############
################        Within ses & timeWin            #######################
#"sub" "seniority" 
ses_vars <- c("wake_morning" , "wake_night")
timeWin_vars <- c("0-100","100-200","200-300","300-400","0-224","224-444","0-48","48-100","100-148","148-200","200-248","248-300","300-348","348-400","400-444")

file_name <- "mm_6_res_diffRF_seniority+1sub_within-SesTimewin.csv"

output_diffRF <- data.frame(ses = character(), timeWin = character(), posNeg = character(), Bayes = numeric(), anovaPval = numeric())
for (i in ses_vars) {
  for (j in timeWin_vars) {
      # Define models
      o_diffRF_pos.null <- lmer(ampAvg_pos_diffRF ~ (1|sub) , data=subset(o_diffRF, timeWin == j & ses==i), REML=FALSE)
      o_diffRF_neg.null <- lmer(ampAvg_neg_diffRF ~ (1|sub) , data=subset(o_diffRF, timeWin == j & ses==i), REML=FALSE)
      o_diffRF_pos.model<-lmer(ampAvg_pos_diffRF ~ seniority + (1|sub) , data=subset(o_diffRF, timeWin == j & ses==i), REML=FALSE)
      o_diffRF_neg.model<-lmer(ampAvg_neg_diffRF ~ seniority  + (1|sub) , data=subset(o_diffRF, timeWin == j & ses==i), REML=FALSE)
      
      # compute Bayes & Anova
      anova_out_pos = anova(o_diffRF_pos.null,o_diffRF_pos.model)
      bayes_out_pos <- bayesfactor_models(o_diffRF_pos.null,o_diffRF_pos.model,denominator=o_diffRF_pos.null) 
      anova_out_neg = anova(o_diffRF_neg.null,o_diffRF_neg.model)
      bayes_out_neg <- bayesfactor_models(o_diffRF_neg.null,o_diffRF_neg.model,denominator=o_diffRF_neg.null) 
    
      #print(paste(j,":"))
      #print(paste("Pos:   Bayes:",exp(bayes_out_pos$log_BF[2]),"     anova Pval: ",anova_out_pos$"Pr(>Chisq)"[2]))
      #print(paste("Neg:   Bayes:",exp(bayes_out_neg$log_BF[2]),"     anova Pval: ",anova_out_neg$"Pr(>Chisq)"[2]))
      
      # Append variables to the data frame
      newEntry_pos <- data.frame(ses = i,timeWin = j,posNeg = "Pos", Bayes = exp(bayes_out_pos$log_BF[2]), anovaPval = anova_out_pos$"Pr(>Chisq)"[2])
      newEntry_neg <- data.frame(ses = i,timeWin = j,posNeg = "Neg", Bayes = exp(bayes_out_neg$log_BF[2]), anovaPval = anova_out_neg$"Pr(>Chisq)"[2])
      output_diffRF <- rbind(output_diffRF, newEntry_pos)
      output_diffRF <- rbind(output_diffRF, newEntry_neg)
  }
}

sortedTable <- output_diffRF[order(output_diffRF$Bayes, decreasing = TRUE), ]
#header <- "lmer(ampAvg ~ seniority*ses +ses + (1|sub) , data=subset(o_diffRF, timeWin == j & ses==i)"
#header_and_tabel <- rbind(header, sortedTable)
write.csv(sortedTable, paste0(output_dir,"\\",file_name))

```

```{r}
################ Doesn't includes variable 'block_type'. Instead includes difference between fixed-rand ##############
################        Within timeWin            #######################
# "ses" "seniority" 
timeWin_vars <- c("0-100","100-200","200-300","300-400","0-224","224-444","0-48","48-100","100-148","148-200","200-248","248-300","300-348","348-400","400-444")

file_name <- "mm_6_res_diffRF_ses+1sub_within-Timewin.csv"

output_diffRF <- data.frame( timeWin = character(), posNeg = character(), Bayes = numeric(), anovaPval = numeric())
for (j in timeWin_vars) {
    # Define models
    o_diffRF_pos.null <- lmer(ampAvg_pos_diffRF ~ (1|sub) , data=subset(o_diffRF, timeWin == j), REML=FALSE)
    o_diffRF_neg.null <- lmer(ampAvg_neg_diffRF ~ (1|sub) , data=subset(o_diffRF, timeWin == j), REML=FALSE)
    o_diffRF_pos.model<-lmer(ampAvg_pos_diffRF ~ ses + (1|sub) , data=subset(o_diffRF, timeWin == j), REML=FALSE)
    o_diffRF_neg.model<-lmer(ampAvg_neg_diffRF ~ ses + (1|sub) , data=subset(o_diffRF, timeWin == j), REML=FALSE)
    
    # compute Bayes & Anova
    anova_out_pos = anova(o_diffRF_pos.null,o_diffRF_pos.model)
    bayes_out_pos <- bayesfactor_models(o_diffRF_pos.null,o_diffRF_pos.model,denominator=o_diffRF_pos.null) 
    anova_out_neg = anova(o_diffRF_neg.null,o_diffRF_neg.model)
    bayes_out_neg <- bayesfactor_models(o_diffRF_neg.null,o_diffRF_neg.model,denominator=o_diffRF_neg.null) 
  
    #print(paste(j,":"))
    #print(paste("Pos:   Bayes:",exp(bayes_out_pos$log_BF[2]),"     anova Pval: ",anova_out_pos$"Pr(>Chisq)"[2]))
    #print(paste("Neg:   Bayes:",exp(bayes_out_neg$log_BF[2]),"     anova Pval: ",anova_out_neg$"Pr(>Chisq)"[2]))
    
    # Append variables to the data frame
    newEntry_pos <- data.frame(timeWin = j,posNeg = "Pos", Bayes = exp(bayes_out_pos$log_BF[2]), anovaPval = anova_out_pos$"Pr(>Chisq)"[2])
    newEntry_neg <- data.frame(timeWin = j,posNeg = "Neg", Bayes = exp(bayes_out_neg$log_BF[2]), anovaPval = anova_out_neg$"Pr(>Chisq)"[2])
    output_diffRF <- rbind(output_diffRF, newEntry_pos)
    output_diffRF <- rbind(output_diffRF, newEntry_neg)
}


sortedTable <- output_diffRF[order(output_diffRF$Bayes, decreasing = TRUE), ]
#header <- "lmer(ampAvg ~ seniority*ses +ses + (1|sub) , data=subset(o_diffRF, timeWin == j & ses==i)"
#header_and_tabel <- rbind(header, sortedTable)
write.csv(sortedTable, paste0(output_dir,"\\",file_name))

```

```{r}
################ Includes variable 'block_type'  #######################
################ Within ses & timeWin            #######################
# "block_type" "seniority" 
timeWin_vars <- c("0-100","100-200","200-300","300-400","0-224","224-444","0-48","48-100","100-148","148-200","200-248","248-300","300-348","348-400","400-444")
output_sepRF <- data.frame(ses = character(), timeWin = character(), posNeg = character(), Bayes = numeric(), anovaPval = numeric())

file_name <- "mm_6_res_sepRF_seniority+1sub_within-SesTimewin.csv"
for (i in ses_vars) {
  for (j in timeWin_vars) {
    # define models
    o_sepRF_pos.null <- lmer(ampAvg_pos ~ (1|sub) , data=subset(o_sepRF, timeWin == j & ses==i), REML=FALSE)
    o_sepRF_neg.null <- lmer(ampAvg_neg ~ (1|sub) , data=subset(o_sepRF, timeWin == j & ses==i), REML=FALSE)
    o_sepRF_neg.model<-lmer(ampAvg_neg ~ seniority + (1|sub), data=subset(o_sepRF, timeWin == j & ses==i), REML=FALSE)
    o_sepRF_pos.model<-lmer(ampAvg_pos ~ seniority + (1|sub) , data=subset(o_sepRF, timeWin == j & ses==i), REML=FALSE)
    
    # compute Bayes & Anova
    anova_out_pos = anova(o_sepRF_pos.null,o_sepRF_pos.model)
    anova_out_neg = anova(o_sepRF_neg.null,o_sepRF_neg.model)
    bayes_out_neg <- bayesfactor_models(o_sepRF_neg.null,o_sepRF_neg.model,denominator=o_sepRF_neg.null) 
    bayes_out_pos <- bayesfactor_models(o_sepRF_pos.null,o_sepRF_pos.model,denominator=o_sepRF_pos.null)
    
    #print(paste(j,"  & ",i,":"))
    #print(paste("Pos:   Bayes:",exp(bayes_out_pos$log_BF[2]),"     anova Pval: ",anova_out_pos$"Pr(>Chisq)"[2]))
    #print(paste("Neg:   Bayes:",exp(bayes_out_neg$log_BF[2]),"     anova Pval: ",anova_out_neg$"Pr(>Chisq)"[2]))
    
    # Append variables to the data frame
    newEntry_pos <- data.frame(ses = i,timeWin = j,posNeg = "Pos", Bayes = exp(bayes_out_pos$log_BF[2]), anovaPval = anova_out_pos$"Pr(>Chisq)"[2])
    newEntry_neg <- data.frame(ses = i,timeWin = j,posNeg = "Neg", Bayes = exp(bayes_out_neg$log_BF[2]), anovaPval = anova_out_neg$"Pr(>Chisq)"[2])
    output_sepRF <- rbind(output_sepRF, newEntry_pos)
    output_sepRF <- rbind(output_sepRF, newEntry_neg)
  }
}

sortedTable <- output_sepRF[order(output_sepRF$Bayes, decreasing = TRUE), ]
#header <- "lmer(ampAvg ~ seniority  + (1|sub) , data=subset(o_sepRF, timeWin == j & ses==i)"
#header_and_tabel <- rbind(header, sortedTable)
write.csv(sortedTable, paste0(output_dir,"\\",file_name))

```
```{r}
################ Includes variable 'block_type'   #######################
################ within timeWin                   #######################
# "ses" "block_type" "seniority" 
timeWin_vars <- c("0-100","100-200","200-300","300-400","0-224","224-444","0-48","48-100","100-148","148-200","200-248","248-300","300-348","348-400","400-444")
output_sepRF <- data.frame(timeWin = character(), posNeg = character(), Bayes = numeric(), anovaPval = numeric())

file_name <- "mm_6_res_sepRF_ses+1sub_within-Timewin.csv"
for (j in timeWin_vars) {
  # define models
  o_sepRF_pos.null <- lmer(ampAvg_pos ~ (1|sub) , data=subset(o_sepRF, timeWin == j ), REML=FALSE)
  o_sepRF_neg.null <- lmer(ampAvg_neg ~ (1|sub) , data=subset(o_sepRF, timeWin == j ), REML=FALSE)
  o_sepRF_neg.model<-lmer(ampAvg_neg ~ ses + (1|sub), data=subset(o_sepRF, timeWin == j), REML=FALSE)
  o_sepRF_pos.model<-lmer(ampAvg_pos ~ ses  + (1|sub) , data=subset(o_sepRF, timeWin == j), REML=FALSE)
  
  # compute Bayes & Anova
  anova_out_pos = anova(o_sepRF_pos.null,o_sepRF_pos.model)
  anova_out_neg = anova(o_sepRF_neg.null,o_sepRF_neg.model)
  bayes_out_neg <- bayesfactor_models(o_sepRF_neg.null,o_sepRF_neg.model,denominator=o_sepRF_neg.null) 
  bayes_out_pos <- bayesfactor_models(o_sepRF_pos.null,o_sepRF_pos.model,denominator=o_sepRF_pos.null)
  
  #print(paste(j,"  & ",i,":"))
  #print(paste("Pos:   Bayes:",exp(bayes_out_pos$log_BF[2]),"     anova Pval: ",anova_out_pos$"Pr(>Chisq)"[2]))
  #print(paste("Neg:   Bayes:",exp(bayes_out_neg$log_BF[2]),"     anova Pval: ",anova_out_neg$"Pr(>Chisq)"[2]))
  
  # Append variables to the data frame
  newEntry_pos <- data.frame(timeWin = j,posNeg = "Pos", Bayes = exp(bayes_out_pos$log_BF[2]), anovaPval = anova_out_pos$"Pr(>Chisq)"[2])
  newEntry_neg <- data.frame(timeWin = j,posNeg = "Neg", Bayes = exp(bayes_out_neg$log_BF[2]), anovaPval = anova_out_neg$"Pr(>Chisq)"[2])
  output_sepRF <- rbind(output_sepRF, newEntry_pos)
  output_sepRF <- rbind(output_sepRF, newEntry_neg)
}

sortedTable <- output_sepRF[order(output_sepRF$Bayes, decreasing = TRUE), ]
#header_and_tabel <- rbind(header, sortedTable)
write.csv(sortedTable, paste0(output_dir,"\\",file_name))

```



