---
title: "R Notebook"
output: html_notebook
---
```{r}
# run twice 
library(Matrix)
library(lme4)
library(lmtest)
library(dplyr)
library(parallel)
library(bayestestR)
library(glmmTMB)
```

```{r}
output_file_name <- "R_glm_N100.txt" # Replace
data_table <- read.csv("D:\\OExpOut\\adapt_res\\comp\\N100_dataToR.csv")  # Replace with your actual file path
choosen_family = gaussian; # Problematic! As gaussian-glm might be just lme

# Convert variables to factors:
data_table$sov <- factor(data_table$sov, levels = c('wn', 'N2', 'N3', 'REM'), ordered = FALSE)
data_table$sub <- factor(data_table$sub, ordered = FALSE)
data_table$cond <- factor(data_table$cond, levels = c('NblT1', 'NblT2', 'NblT3', 'NblT4'), ordered = FALSE)
data_table$comp_amp <- as.numeric(data_table$comp_amp)  # Convert comp_amp to numeric

#### Remove outliers:
std_to_remove_outliers <- 4 
mean_comp_amp <- mean(data_table$comp_amp, na.rm = TRUE)
sd_comp_amp <- sd(data_table$comp_amp, na.rm = TRUE)
outliers <- data_table[abs(data_table$comp_amp - mean_comp_amp) > std_to_remove_outliers * sd_comp_amp, ]
print("Details of removed outliers:")
print(outliers)
data_table <- data_table[abs(data_table$comp_amp - mean_comp_amp) <= std_to_remove_outliers * sd_comp_amp, ]
```

```{r}

# Model Fitting Using glmmTMB with tweedie Distribution---
model_tweedie <- glmmTMB(comp_amp ~ sov * cond + (1 | sub), data = data_table,family = tweedie(link = "log"))
model_nor <- glmmTMB(comp_amp ~ sov * cond + (1 | sub), data = data_table,family = gaussian)

# Extract the Tweedie power parameter 
# would be between 1-2 not normal. Normal is 0
print('model_tweedie log model')
power_param <- family_params(model_tweedie)
print(power_param)

print('gaussian model')
# Extract the Gauusain power parameter - sanity check should be 0 for gaussian
power_param <- family_params(model_nor)
print(power_param)

print(summary(model_tweedie))
print(summary(model_nor))

print(summary(anova(model_tweedie,model_nor)))

bayes_out_tweedie <- bayesfactor_models(model_tweedie, denominator = 1)
bayes_out_nor <- bayesfactor_models(model_nor, denominator = 1)

# Print the inverse Bayes factor values for easier interpretation
print(1 / as.numeric(bayes_out_tweedie))
print(1 / as.numeric(bayes_out_nor))


bayes_model_comparison <- bayesfactor_models(model_tweedie,model_nor)
print(bayes_model_comparison)


# Q-Q plot for normality of residuals
qqnorm(residuals(model_nor))
qqline(residuals(model_nor))
# Residuals vs. Fitted plot for homoscedasticity
plot(fitted(model_nor), residuals(model_nor))
abline(h = 0, col = "red")


# Q-Q plot for normality of residuals
qqnorm(residuals(model_tweedie))
qqline(residuals(model_tweedie))
# Residuals vs. Fitted plot for homoscedasticity
plot(fitted(model_tweedie), residuals(model_tweedie))
abline(h = 0, col = "red")

```

```{r}
### Preform modeling
sink(output_file_name)  # Redirect console output to a text file


# Fit the linear mixed-effects models
models <- list(
  glmmTMB(comp_amp ~ -1 + (1 | sub), data = data_table,family = choosen_family),
  glmmTMB(comp_amp ~ -1 + cond + (1 | sub), data = data_table,family = choosen_family),
  glmmTMB(comp_amp ~ -1 + sov + (1 | sub), data = data_table,family = choosen_family),
  glmmTMB(comp_amp ~ -1 + sov + cond + (1 | sub), data = data_table,family = choosen_family),
  glmmTMB(comp_amp ~ -1 + sov * cond + (1 | sub), data = data_table,family = choosen_family)
)

# Manually specify pairs of models to compare
model_pairs <- list(c(1, 2), c(1, 3),c(2, 3), c(3, 4),c(2, 4),c(4,5))

# Model names for clarity
model_names <- c("Model 1: (1 | sub)",
                 "Model 2: cond + (1 | sub)",
                 "Model 3: sov + (1 | sub)",
                 "Model 4: sov + cond + (1 | sub)",
                 "Model 5: sov * cond + (1 | sub)")


# Print models 
for (i in seq_along(models)) {
  cat(model_names[i], "\n")
  print(models[[i]])
  cat("\n\n")
  print(shapiro.test(residuals(models[[i]])))
  cat("\n\n")  # Add two newlines
  # boot_results <- analyze_lme_model(models[[i]])
  # cat("\n\n")  # Add two newlines
  cat("=================================\n\n")
}

# Print anova and Bayes models pair comparison results 
for (pair in model_pairs) {
  cat("Anova Comparing", model_names[pair[1]], "with", model_names[pair[2]], "\n")
  print(anova(models[[pair[1]]], models[[pair[2]]]))
  cat("\n\n")
  cat("Bayes Comparing", model_names[pair[1]], "with", model_names[pair[2]], "\n")
  print(bayesfactor_models(models[[pair[1]]], models[[pair[2]]]))
  cat("\n\n")
}

# Compare all models together
cat("Anova Comparison of all models:\n")
print(summary(do.call(anova, models)))
cat("\n\nBayes Comparison of all models:\n")
print(summary(do.call(bayesfactor_models, models)))
cat("\n\n")

# stop redirecting output
sink()

```